"""Seventh Migration

Revision ID: 2ff505363561
Revises: 30e251bf0d8a
Create Date: 2019-02-13 10:56:20.679611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff505363561'
down_revision = '30e251bf0d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('post', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'posts', ['post'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post')
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
