"""Seventh Migration

Revision ID: 30e251bf0d8a
Revises: 72387362130d
Create Date: 2019-02-13 10:54:17.423549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e251bf0d8a'
down_revision = '72387362130d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_post_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_post_fkey', 'comments', 'posts', ['post'], ['id'])
    # ### end Alembic commands ###
