"""Fourth Migration

Revision ID: 593c71895768
Revises: f9448651ff4e
Create Date: 2019-02-10 11:39:21.905024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593c71895768'
down_revision = 'f9448651ff4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date')
    # ### end Alembic commands ###
