"""Seventh Migration

Revision ID: 72387362130d
Revises: 76aeb7d41dfd
Create Date: 2019-02-13 10:07:52.955242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72387362130d'
down_revision = '76aeb7d41dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post', sa.Integer(), nullable=True))
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post'], ['id'])
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    op.drop_column('comments', 'post')
    # ### end Alembic commands ###
