"""Third Migration

Revision ID: be66e979ea06
Revises: 5caee86d2e08
Create Date: 2019-02-09 17:02:58.647700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be66e979ea06'
down_revision = '5caee86d2e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_date'), 'posts', ['date'], unique=False)
    op.drop_index('ix_posts_timestamp', table_name='posts')
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_posts_date'), table_name='posts')
    op.drop_column('posts', 'date')
    # ### end Alembic commands ###
